src/groups/urls.py
from django.urls import path

from groups import views

app_name = 'groups'

urlpatterns = [
    path('', views.home, name='home'),
    path('index/', views.group_app, name='index'),
    path('list/', views.groups, name='list'),
    path('create/', views.create_group, name='create'),
    path('edit/<int:pk>/', views.edit_group, name='edit'),
    path('remove/<int:pk>/', views.remove_group, name='remove'),
    path('generate/', views.generate_group, name='generate'),
]

src/students_tracker/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path

from students import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.home, name='home'),
    path('students/', include('students.urls'), name='students'),
    path('teachers/', include('teachers.urls'), name='teachers'),
    path('groups/', include('groups.urls'), name='groups'),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

    urlpatterns += [url(r'^silk/', include('silk.urls', namespace='silk'))]

src/groups/models.py
from django.db import models


class Group(models.Model):
    FACULTY = [
        ('Music', 'Music'),
        ('Art and Design', 'Art and Design'),
        ('Medicine', 'Medicine'),
        ('Law', 'Law'),
        ('Forestry', 'Forestry'),
        ('Arts and Humanity', 'Arts and Humanity'),
        ('Dentistry', 'Dentistry'),

    ]
    FACULTY_N_SPECIALIZATION = [
        ('Music', (
            ('Theatre Faculty', 'Theatre Faculty'),
            ('Film and TV', 'Film and TV'),
            ('Music and Dance Faculty', 'Music and Dance Faculty'),
        )
         ),
        ('Art and Design', (
            ('Digital Arts', 'Digital Arts'),
            ('Electronic Integrated Arts', 'Electronic Integrated Arts'),
            ('Art & Design', 'Art & Design'),
            ('Ceramic Art', 'Ceramic Art'),
        )
         ),
        ('Medicine', (
            ('Critical Care Medicine', 'Critical Care Medicine'),
            ('Pain Medicine', 'Pain Medicine'),
            ('Pediatric Anesthesiology', 'Pediatric Anesthesiology'),
            ('Obstetric Anesthesiology', 'Obstetric Anesthesiology'),
        )
         ),
        ('Law', (
            ('Law and Sexuality', 'Law and Sexuality'),
            ('International and Comparative Law', 'International and Comparative Law'),
            ('Human Rights', 'Human Rights'),
            ('Media, Entertainment', 'Media, Entertainment'),
            ('Law and Philosophy', 'Law and Philosophy'),
        )
         ),
        ('Forestry', (
            ('Forestry', 'Forestry'),
            ('Natural Resources', 'Natural Resources'),
            ('Wildlife Sciences', 'Wildlife Sciences'),
        )
         ),
        ('Arts and Humanity', (
            ('Commerce,Law and Management', 'Commerce,Law and Management'),
            ('Engineering and the Built Environment', 'Engineering and the Built Environment'),
            ('Health Sciences', 'Health Sciences'),
            ('Science', 'Science'),
            ('Humanities', 'Humanities'),
        )
         ),
        ('Dentistry', (
            ('Orthopedic dentistry', 'Orthopedic dentistry'),
            ('Propedeutics of therapeutic dentistry', 'Propedeutics of therapeutic dentistry'),
            ('Propaedeutics of pediatric therapeutic dentistry', 'Propaedeutics of pediatric therapeutic dentistry'),
            ('Therapeutic dentistry', 'Therapeutic dentistry'),
            ('Pediatric therapeutic dentistry', 'Pediatric therapeutic dentistry'),
            ('Prevention of dental diseases', 'Prevention of dental diseases'),
        )
         ),
    ]

    faculty = models.CharField(max_length=64, choices=FACULTY)
    degree_specialization = models.CharField(max_length=64, choices=FACULTY_N_SPECIALIZATION)
    course = models.IntegerField()
    head = models.OneToOneField('students.Student', on_delete=models.SET_NULL, null=True)
    supervisor = models.ForeignKey('teachers.Teacher', on_delete=models.SET_NULL, null=True)

    def info(self) -> str:
        return f'{self.id} {self.faculty} {self.degree_specialization} {self.course}'

    def __str__(self):
        return f'{self.id}, {self.faculty}'

    def __repr__(self):
        return f'{self.id}, {self.faculty}, {self.degree_specialization}'

src/groups/forms.py
from django import forms

from groups.models import Group


class GroupCreateForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = (
            'faculty',
            'degree_specialization',
            'course',
            'head',
            'supervisor',
        )

    def clean_course(self):  # clean_ + field
        course = self.cleaned_data['course']
        if not 1 <= course <= 5:
            raise forms.ValidationError('Choose between 1-5')
        return course

    def clean_faculty(self):  # clean_ + field
        faculty = self.cleaned_data['faculty']
        return faculty

    def clean_degree_specialization(self):
        degree_specialization = self.cleaned_data['degree_specialization']
        related_data = {i[0]: i[1] for i in Group.FACULTY_N_SPECIALIZATION}
        faculty = self.clean_faculty()
        check_related = related_data.get(faculty)
        for spec in check_related:
            if spec[0] == degree_specialization:
                return degree_specialization
        raise forms.ValidationError(f'{degree_specialization} does not belong to {faculty}')

src/groups/views.py
import random

from django.apps import apps
from django.contrib import messages
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from groups.filters import GroupFilter
from groups.forms import GroupCreateForm
from groups.models import Group

from utils import clear_table_parser, parse_usr_value


def home(request):
    return render(request, 'index.html')


def group_app(request):  # main page
    return render(request, 'group_index.html')


def groups(request):
    count = Group.objects.count()
    groups_queryset_list = Group.objects.all().select_related('head', 'supervisor')

    gr_filter = GroupFilter(request.GET, queryset=groups_queryset_list)
    groups_queryset_list = gr_filter.qs

    paginator = Paginator(groups_queryset_list, 10)
    page = request.GET.get('page')
    try:
        groups_queryset = paginator.page(page)
    except PageNotAnInteger:
        groups_queryset = paginator.page(1)
    except EmptyPage:
        groups_queryset = paginator.page(paginator.num_pages)

    context = {'groups': groups_queryset, 'count': count, 'gr_filter': gr_filter}

    return render(request, 'groups_list.html', context=context)


def generate_group(request):
    set_params = {i[0]: i[1] for i in Group.FACULTY_N_SPECIALIZATION}
    set_faculty = random.choice(list(set_params.keys()))
    set_degree = random.choice(list(set_params.get(set_faculty)))
    group = Group.objects.create(
        faculty=set_faculty,
        degree_specialization=set_degree[1],
        course=random.randint(1, 5),
    )

    return render(request, 'generate_group.html', context={'group': group})


def sheets(request):  # abandoned
    sheets_reg = [
        m._meta.db_table for c in apps.get_app_configs() for m in c.get_models()
    ]
    response = f'Current sheets: {sheets_reg}<br/>'
    return HttpResponse(response)


def clear_sheet(request):  # abandoned
    """
    :param request:
    /clear_sheet/gr/?clear=1&sheet_name=Group
    :return:
    Wipes out all rows in sheet Group
    """
    req_clear_sheet = clear_table_parser(request.GET['clear'], 'digit')
    sheet_name = clear_table_parser(request.GET['sheet_name'], 'alpha')
    response = f'Selected SHEET has been cleared:<br/>'
    if sheet_name == 'Group':
        if req_clear_sheet == 1:
            Group.objects.all().delete()
            response += f'{sheet_name}'

    return HttpResponse(response)


def delete_row(request):  # abandoned
    """
    :param request:
    /del_row/gr/?id=49
    :return:
    Wipes out selected row from current table
    """
    req_clear_row = clear_table_parser(request.GET['id'], 'id')
    try:
        Group.objects.filter(id=req_clear_row).delete()
        response = f'Selected ROW has been cleared: {req_clear_row}<br/>'
    except Exception:
        response = f'Something went wrong. Enter valid value'

    return HttpResponse(response)


def query_filter(request):  # abandoned
    """
    :param request:
    /filter/tc/?age=50&first_name=Elizabeth
    /filter/gr/?order_by=course
    /filter/gr/?course=2&order_by=-faculty
    :return:
    list of teachers with params equal to request:
    id, faculty, degree_specialization, course...
    """
    params = [
        'course',
        'course__gt',
        'course__lt',
        'course__lte',
        'course__gte',
        'faculty',
        'faculty__exact',
        'faculty__startswith',
        'faculty__endswith',
        'degree_specialization',
        'degree_specialization__startswith',
        'degree_specialization__endswith',
        'id',
        'order_by',
    ]

    response = f'Selected data:<br/>'
    groups_queryset = Group.objects.all()

    # simple filter

    for param in params:
        value = request.GET.get(param)
        if param not in 'order_by':
            if value:
                groups_queryset = groups_queryset.filter(**{param: value})

    # adds filter order_by

    for param in params:
        value = request.GET.get(param)
        if param in 'order_by':
            if value:
                groups_queryset = groups_queryset.order_by(value)

    for group in groups_queryset:
        response += group.info() + '<br/>'

    return HttpResponse(response)


def generate_groups(request):  # abandoned
    """
    :param request:
    PATH: /generate_groups/gr/?count=10
    :return:
    list of 10 groups: id, faculty, degree_specialization, course.
    """
    rand_groups_queryset = Group.objects.all()
    response = f'Groups:<br/>'
    usr_value = parse_usr_value(request.GET['count'])
    if type(usr_value) is str:
        return HttpResponse(usr_value)

    for _ in range(usr_value):
        set_params = {i[0]: i[1] for i in Group.FACULTY_N_SPECIALIZATION}
        set_faculty = random.choice(list(set_params.keys()))
        set_degree = random.choice(list(set_params.get(set_faculty)))
        groups.append(Group(
            faculty=set_faculty,
            degree_specialization=set_degree[1],
            course=random.randint(1, 5),
        ))
    Group.objects.bulk_create(groups)

    for group in rand_groups_queryset:
        response += group.info() + '<br/>'

    return HttpResponse(response)


def create_group(request):
    if request.method == 'POST':

        form = GroupCreateForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, 'You have successfully created group')
            return HttpResponseRedirect(reverse('groups:list'))
    else:
        form = GroupCreateForm()

    context = {'form': form}

    return render(request, 'create_group.html', context=context)


def edit_group(request, pk):
    group = get_object_or_404(Group, id=pk)
    if request.method == 'POST':

        form = GroupCreateForm(request.POST, instance=group)

        if form.is_valid():
            form.save()
            messages.success(request, 'You have successfully changed group')
            return HttpResponseRedirect(reverse('groups:list'))
    else:
        form = GroupCreateForm(instance=group)

    context = {'form': form, 'group': group}

    return render(request, 'edit_group.html', context=context)


def remove_group(request, pk):
    group = get_object_or_404(Group, id=pk)
    group.delete()
    messages.success(request, 'You have successfully deleted group')

    return HttpResponseRedirect(reverse('groups:list'))

src/groups/templates/create_group.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hillel project</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/group.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Righteous&subset=latin,cyrillic" rel="stylesheet"
          type="text/css">
</head>
<body>

<div class="page-header">
    <h1><a> Create group </a></h1>
</div>
<div class="content container">
    <form method="post" style="font-size: 15px;">
        {% csrf_token %}
        {{ create_form.as_p }}
        <button type="submit"> Submit </button>
    </form>
</div>


</body>
</html>

src/groups/templates/edit_group.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Groups</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/group.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Righteous&subset=latin,cyrillic" rel="stylesheet"
          type="text/css">
    <link href="{% static 'css/group.css' %}" type="text/css" rel="stylesheet">
</head>
<body>
<div class="page-header">
    <h1>Edit group</h1>
</div>
<div class="content-container">
    {% include 'messages.html' %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="button" name="submit" type="submit"> submit</button>
        <button class="button" type="reset"> reset </button>
        <a href="{% url 'groups:list' %}"><button class="button" type="button"> cancel </button></a>
        <a href="{% url 'groups:remove' pk=group.id %}"><button class="button-del" type="button"> delete </button></a><br>

    </form>
</div>
</body>
</html>

src/groups/templates/g_index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create group</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/group.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Righteous&subset=latin,cyrillic" rel="stylesheet"
          type="text/css">
    <link href="group.css" type="text/css" rel="stylesheet">
</head>
<body>
    <div class="page-header">
        <h1><a>Create forms:</a></h1>
    </div>
    <div class="post">
        <a href="/group/create_group/" style="font-size: 20px;">Create Group</a>
    </div>
</body>
</html>

src/groups/templates/generate_group.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hillel project</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/group.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Righteous&subset=latin,cyrillic" rel="stylesheet"
          type="text/css">
    <link href="{% static 'css/group.css' %}" type="text/css" rel="stylesheet">
</head>
<body>
    <div class="page-header">
        <h1>Group Info</h1>
    </div>
    <div class="content-container">
        <h3 align="center">Group: {{ group.info }}</h3>
        <a href="{% url 'groups:generate' %}"><button class="button" name="submit" type="submit"> generate </button></a>
        <a href="{% url 'groups:index' %}"><button class="button" name="submit" type="submit"> cancel </button></a>
    </div>

</body>
</html>

src/groups/templates/group_index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Group</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/group.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Righteous&subset=latin,cyrillic" rel="stylesheet"
          type="text/css">
    <link href="{% static 'css/group.css' %}" type="text/css" rel="stylesheet">
</head>
<body>
    <div class="header">
        <h1>Group APP</h1>
    </div>
    <div class="content">
        <ul>
            <li><a href="{% url 'home' %}" style="font-size: 20px;">Home</a></li>
            <li><a href="{% url 'groups:list' %}" style="font-size: 20px;">Groups List</a></li>
            <li><a href="{% url 'groups:create' %}" style="font-size: 20px;">Create group</a></li>
            <li><a href="{% url 'groups:generate' %}" style="font-size: 20px;">Generate group</a></li>
            <li style="float:right"><a class="active" href="#about">About</a></li>
        </ul>
    </div>
</body>
</html>

src/groups/templates/groups_list.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Groups</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/group.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Righteous&subset=latin,cyrillic" rel="stylesheet"
          type="text/css">
    <link href="{% static 'css/group.css' %}" type="text/css" rel="stylesheet">
</head>
<body>
     <div class="header">
        <h1>Groups List</h1>
    </div>

    {% include 'messages.html' %}

    <div class="links" align="center">
        <a href="{% url 'home' %}" style="font-size: 20px;">Home &ensp;</a>
        <a href="{% url 'groups:index' %}" style="font-size: 20px;">Groups app &ensp;</a>
        <a href="{% url 'groups:create' %}" style="font-size: 20px;">Create group &ensp;</a>
    </div>
     <h2>Groups count: {{ count }}</h2>
    <div>
        <form method="get">
            {{gr_filter.form}}
            <button class="button-table" type="submit">Search</button>
        </form>
    </div>
     <div class="table">
        <table style="width:100%">
            <tr>
                <th style="width:130px">Id</th>
                <th>Faculty</th>
                <th style="width:500px">Specialization</th>
                <th>Course</th>
                <th>Head</th>
                <th>Supervisor</th>
                <th style="width:200px">Action</th>
                </tr>
            {% for group in groups %}
                <tr>
                <td style="text-align: center">{{ group.id }}</td>
                <td>{{ group.faculty }}</td>
                <td>{{ group.degree_specialization }}</td>
                <td style="text-align: center">{{ group.course }}</td>
                <td>{{ group.head }}</td>
                <td>{{ group.supervisor }}</td>
                <td style="text-align: center">
                <a href="{% url 'groups:edit' pk=group.id %}"><button class="button-table"> edit </button></a>
                <a href="{% url 'groups:remove' pk=group.id %}"><button class="button-table-del"> delete </button></a><br>
                </td>
                </tr>
            {% endfor %}
        </table>
     </div>
     <div class="pagination">
         <span class="step-links">
             {% if groups.has_previous %}
             <a href="?page=1">&laquo; first</a>
             <a href="?page={{ groups.previous_page_number }}">previous</a>
             {% endif %}

             <span class="current">
                 Page {{ groups.number }} of {{ groups.paginator.num_pages }}.
             </span>

             {% if groups.has_next %}
             <a href="?page={{ groups.next_page_number }}">next</a>
             <a href="?page={{ groups.paginator.num_pages }}">last &raquo;</a>
             {% endif %}
         </span>
     </div>
</body>
</html>

src/groups/templates/messages.html
{% if messages %}
    {% for message in messages %}
       <div class="alert alert-{{ message.tags }} m-2" id="msg" role="alert">
           {{ message }}
       </div>
    {% endfor %}
{% endif %}