src/groups/urls.py
from django.urls import path

from groups import views

app_name = 'groups'

urlpatterns = [
    path('', views.home, name='home'),
    path('index/', views.group_app, name='index'),
    path('list/', views.groups, name='list'),
    path('create/', views.create_group, name='create'),
    path('edit/<int:pk>/', views.edit_group, name='edit'),
    path('remove/<int:pk>/', views.remove_group, name='remove'),
    path('generate/', views.generate_group, name='generate'),
]

src/students_tracker/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path

from students import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.home, name='home'),
    path('students/', include('students.urls'), name='students'),
    path('teachers/', include('teachers.urls'), name='teachers'),
    path('groups/', include('groups.urls'), name='groups'),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

    urlpatterns += [url(r'^silk/', include('silk.urls', namespace='silk'))]

src/teachers/urls.py
from django.urls import path

from teachers import views

app_name = 'teachers'

urlpatterns = [
    path('', views.home, name='home'),
    path('index/', views.teacher_app, name='index'),
    path('list/', views.teachers, name='list'),
    path('create/', views.create_teacher, name='create'),
    path('edit/<int:pk>/', views.edit_teacher, name='edit'),
    path('remove/<int:pk>/', views.remove_teacher, name='remove'),
    path('generate/', views.generate_teacher, name='generate'),
]

src/teachers/models.py
import random

from django.db import models

from faker import Faker


class Teacher(models.Model):
    PROFESSOR = 'PR'
    ASSOCIATE_PROFESSOR = 'AEP'
    ASSISTANT_PROFESSOR = 'ASP'
    MASTER_INSTRUCTOR = 'MI'
    SENIOR_INSTRUCTOR = 'SI'
    INSTRUCTOR = 'IR'
    RESEARCH_ASSOCIATE = 'RA'
    LECTURER = 'LR'

    TEACHERS_RANK = [
        (PROFESSOR, 'Professor'),
        (ASSOCIATE_PROFESSOR, 'Associate Professor'),
        (ASSISTANT_PROFESSOR, 'Assistant Professor'),
        (MASTER_INSTRUCTOR, 'Master Instructor'),
        (SENIOR_INSTRUCTOR, 'Senior Instructor'),
        (INSTRUCTOR, 'Instructor'),
        (RESEARCH_ASSOCIATE, 'Research Associate'),
        (LECTURER, 'Lecturer'),
    ]
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    age = models.PositiveSmallIntegerField()
    rank = models.CharField(max_length=3, choices=TEACHERS_RANK, default='LR')
    email = models.EmailField(unique=True, null=True)
    phone = models.CharField(max_length=24, default='')

    @property
    def full_name(self) -> str:
        return f'{self.first_name} {self.last_name}'

    def info(self) -> str:
        return f'{self.id} {self.first_name} {self.last_name} {self.age} {self.rank}'

    def __str__(self):
        return f'{self.id}, {self.full_name}'

    def __repr__(self):
        return f'{self.id}, {self.full_name}, {self.rank}'

    @classmethod
    def add_teacher(cls):
        fake = Faker()
        teacher = cls.objects.create(
            first_name=fake.first_name(),
            last_name=fake.last_name(),
            age=random.randint(18, 25),
            rank=random.choice(Teacher.TEACHERS_RANK)[0],
            email=fake.email(),
            phone=fake.phone_number(),
        )
        return teacher

src/teachers/forms.py
from django import forms

from teachers.models import Teacher


class TeacherCreateForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = (
            'first_name',
            'last_name',
            'age',
            'rank',
            'email',
            'phone',
        )

    def clean_age(self):  # clean_ + field
        course = self.cleaned_data['age']
        if not 18 <= course <= 99:
            raise forms.ValidationError('You are either too young or too old')
        return course

    def clean_phone(self):  # clean_ + field
        phone = self.cleaned_data['phone']
        if not phone.isdigit():
            raise forms.ValidationError('Phone number must contain only digits')
        return phone

    def clean_first_name(self):
        first_name = self.cleaned_data['first_name']
        if not first_name.isalpha():
            raise forms.ValidationError('First name must contain only letters')
        return first_name

    def clean_last_name(self):  # Petr 1 - not allowed
        last_name = self.cleaned_data['last_name']
        if not last_name.isalpha():
            raise forms.ValidationError('Last name must contain only letters')
        return last_name

    def clean_email(self):
        email = self.cleaned_data['email']
        check_existence = Teacher.objects.all().only('email').filter(email__iexact=email).exclude(email__iexact=email)
        if len(check_existence) != 0:
            raise forms.ValidationError(f'{email} already exists')
        return email

src/teachers/views.py
import random

from django.apps import apps
from django.contrib import messages
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from faker import Faker

from teachers.filters import TeacherFilter
from teachers.forms import TeacherCreateForm
from teachers.models import Teacher

from utils import clear_table_parser, parse_usr_value


def home(request):
    return render(request, 'index.html')


def teacher_app(request):  # main page
    return render(request, 'teacher_index.html')


def teachers(request):
    count = Teacher.objects.count()
    teachers_queryset_list = Teacher.objects.all()

    t_filter = TeacherFilter(request.GET, queryset=teachers_queryset_list)
    teachers_queryset_list = t_filter.qs

    paginator = Paginator(teachers_queryset_list, 10)
    page = request.GET.get('page')
    try:
        teachers_queryset = paginator.page(page)
    except PageNotAnInteger:
        teachers_queryset = paginator.page(1)
    except EmptyPage:
        teachers_queryset = paginator.page(paginator.num_pages)

    context = {'teachers': teachers_queryset, 'count': count, 't_filter': t_filter}

    return render(request, 'teachers_list.html', context=context)


def generate_teacher(request):
    fake = Faker()
    teacher = Teacher.objects.create(
        first_name=fake.first_name(),
        last_name=fake.last_name(),
        age=random.randint(25, 75),
        rank=random.choice(Teacher.TEACHERS_RANK)[0],
        email=fake.email(),
        phone=fake.phone_number(),
    )
    return render(request, 'generate_teacher.html', context={'teacher': teacher})


def sheets(request):  # abandoned
    sheets_reg = [
        m._meta.db_table for c in apps.get_app_configs() for m in c.get_models()
    ]
    response = f'Current sheets: {sheets_reg}<br/>'
    return HttpResponse(response)


def clear_sheet(request):  # abandoned
    """
    :param request:
    /clear_sheet/tc/?clear=1&sheet_name=Teacher
    :return:
    Wipes out all rows in sheet Teacher
    """
    req_clear_sheet = clear_table_parser(request.GET['clear'], 'digit')
    sheet_name = clear_table_parser(request.GET['sheet_name'], 'alpha')
    response = f'Selected SHEET has been cleared:<br/>'
    if sheet_name == 'Teacher':
        if req_clear_sheet == 1:
            Teacher.objects.all().delete()
            response += f'{sheet_name}'
    return HttpResponse(response)


def delete_row(request):  # abandoned
    """
    :param request:
    /del_row/tc/?id=49
    :return:
    Wipes out selected row from current table
    """
    req_clear_row = clear_table_parser(request.GET['id'], 'id')
    try:
        Teacher.objects.filter(id=req_clear_row).delete()
        response = f'Selected ROW has been cleared: {req_clear_row}<br/>'
    except Exception:
        response = f'Something went wrong. Enter valid value'

    return HttpResponse(response)


def query_filter(request):  # abandoned
    """
    :param request:
    /filter/tc/?age=50&first_name=Elizabeth
    /filter/tc/?order_by=age
    /filter/tc/?age=20&order_by=-first_name
    :return:
    list of teachers with params equal to request:
    id, first_name, last_name, age, rank, etc..
    """
    params = [
        'age',
        'age__gt',
        'age__lt',
        'age__lte',
        'age__gte',
        'first_name',
        'first_name__exact',
        'first_name__startswith',
        'first_name__endswith',
        'last_name',
        'last_name__startswith',
        'last_name__endswith',
        'rank',
        'rank__startswith',
        'rank__endswith',
        'id',
        'order_by',
    ]

    response = f'Selected data:<br/>'
    teachers_queryset = Teacher.objects.all()

    # simple filter

    for param in params:
        value = request.GET.get(param)
        if param not in 'order_by':
            if value:
                teachers_queryset = teachers_queryset.filter(**{param: value})

    # adds filter order_by

    for param in params:
        value = request.GET.get(param)
        if param in 'order_by':
            if value:
                teachers_queryset = teachers_queryset.order_by(value)

    for teacher in teachers_queryset:
        response += teacher.info() + '<br/>'

    return HttpResponse(response)


def generate_teachers(request):  # abandoned
    """
    :param request:
    generate_teachers/tc/?count=10
    :return:
    list of 10 teachers: id, first_name, last_name, age, rank.
    """
    fake = Faker()
    rand_teachers_queryset = Teacher.objects.all()
    response = f'Teachers:<br/>'
    usr_value = parse_usr_value(request.GET['count'])
    if type(usr_value) is str:
        return HttpResponse(usr_value)

    for _ in range(usr_value):
        Teacher.objects.create(
            first_name=fake.first_name(),
            last_name=fake.last_name(),
            age=random.randint(25, 75),
            rank=random.choice(Teacher.TEACHERS_RANK)[0],
            email=fake.email(),
            phone=fake.phone_number(),
        )

    for teacher in rand_teachers_queryset:
        response += teacher.info() + '<br/>'

    return HttpResponse(response)


def create_teacher(request):
    from teachers.forms import TeacherCreateForm

    if request.method == 'POST':

        form = TeacherCreateForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, 'You have successfully created teacher')
            return HttpResponseRedirect(reverse('teachers:list'))
    else:
        form = TeacherCreateForm()

    context = {'form': form}

    return render(request, 'create_teacher.html', context=context)


def edit_teacher(request, pk):
    teacher = get_object_or_404(Teacher, id=pk)
    if request.method == 'POST':

        form = TeacherCreateForm(request.POST, instance=teacher)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('teachers:list'))
    else:
        form = TeacherCreateForm(instance=teacher)

    context = {'form': form, 'teacher': teacher}

    return render(request, 'edit_teacher.html', context=context)


def remove_teacher(request, pk):
    teacher = get_object_or_404(Teacher, id=pk)
    teacher.delete()
    messages.success(request, 'You have successfully deleted teacher')

    return HttpResponseRedirect(reverse('teachers:list'))

src/teachers/templates/create_teacher.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hillel project</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/teacher.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Righteous&subset=latin,cyrillic" rel="stylesheet"
          type="text/css">
</head>
<body>

<div class="page-header">
    <h1><a>Create teacher</a></h1>
</div>
<div class="content container">
    <form method="post" style="font-size: 15px;">
        {% csrf_token %}
        {{ create_form.as_p }}
        <button type="submit"> Submit</button>
    </form>
</div>


</body>
</html>

src/teachers/templates/edit_teacher.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Teachers</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/teacher.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Righteous&subset=latin,cyrillic" rel="stylesheet"
          type="text/css">
    <link href="{% static 'css/teacher.css' %}" type="text/css" rel="stylesheet">
</head>
<body>
<div class="page-header">
    <h1>Edit teacher</h1>
</div>
<div class="content-container">
    {% include 'messages.html' %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="button" name="submit" type="submit"> submit</button>
        <button class="button" type="reset"> reset </button>
        <a href="{% url 'teachers:list' %}"><button class="button" type="button"> cancel </button></a>
        <a href="{% url 'teachers:remove' pk=teacher.id %}"><button class="button-del" type="button"> delete </button></a><br>
    </form>
</div>
</body>
</html>

src/teachers/templates/generate_teacher.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hillel project</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/teacher.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Righteous&subset=latin,cyrillic" rel="stylesheet"
          type="text/css">
    <link href="{% static 'css/teacher.css' %}" type="text/css" rel="stylesheet">
</head>
<body>
    <div class="page-header">
        <h1>Teacher Info</h1>
    </div>
    <div class="content-container">
        <h3 align="center">Teacher: {{ teacher.info }}</h3>
        <a href="{% url 'teachers:generate' %}"><button class="button" name="submit" type="submit"> generate </button></a>
        <a href="{% url 'teachers:index' %}"><button class="button" name="submit" type="submit"> cancel </button></a>
    </div>
</body>
</html>

src/teachers/templates/messages.html
{% if messages %}
    {% for message in messages %}
       <div class="alert alert-{{ message.tags }} m-2" id="msg" role="alert">
           {{ message }}
       </div>
    {% endfor %}
{% endif %}

src/teachers/templates/t_index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create student</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/teacher.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Righteous&subset=latin,cyrillic" rel="stylesheet"
          type="text/css">
    <link href="teacher.css" type="text/css" rel="stylesheet">
</head>
<body>
    <div class="page-header">
        <h1><a>Create forms:</a></h1>
    </div>
    <div class="post">
        <a href="/create/" style="font-size: 20px;">Create Teacher</a>
    </div>
</body>
</html>

src/teachers/templates/teacher_index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Teacher</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/teacher.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Righteous&subset=latin,cyrillic" rel="stylesheet"
          type="text/css">
    <link href="{% static 'css/teacher.css' %}" type="text/css" rel="stylesheet">
</head>
<body>
    <div class="header" id="st-header">
        <h1>Teachers APP</h1>
    </div>
    <div class="content">
        <ul>
            <li><a href="{% url 'home' %}" style="font-size: 20px;">Home</a></li>
            <li><a href="{% url 'teachers:list' %}" style="font-size: 20px;">Teachers List</a></li>
            <li><a href="{% url 'teachers:create' %}" style="font-size: 20px;">Create teacher</a></li>
            <li><a href="{% url 'teachers:generate' %}" style="font-size: 20px;">Generate teacher</a></li>
            <li style="float:right"><a class="active" href="#about">About</a></li>
        </ul>
    </div>
</body>
</html>

src/teachers/templates/teachers_list.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Teacher</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/teacher.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Righteous&subset=latin,cyrillic" rel="stylesheet"
          type="text/css">
    <link href="{% static 'css/teacher.css' %}" type="text/css" rel="stylesheet">
</head>
<body>
    <div class="header" id="st-header">
        <h1>Teachers list</h1>
    </div>
    {% include 'messages.html' %}
    <div class="links" align="center">
        <a href="{% url 'home' %}" style="font-size: 20px;">Home &ensp;</a>
        <a href="{% url 'teachers:index' %}" style="font-size: 20px;">Teachers app &ensp;</a>
        <a href="{% url 'teachers:create' %}" style="font-size: 20px;">Create teacher  &ensp;</a>
    </div>
    <h2>Teachers: {{ count }}</h2>
    <div>
        <form method="get">
            {{t_filter.form}}
            <button class="button-table" type="submit">Search</button>
        </form>
    </div>
    <div class="content">
        <table style="width:100%">
            <tr>
                <th style="width:130px">Id</th>
                <th>First name</th>
                <th>Last name</th>
                <th>Age</th>
                <th>Rank</th>
                <th>Phone</th>
                <th style="width:20%">Email</th>
                <th>Group</th>
                <th style="width:200px">Action</th>
                </tr>
            {% for teacher in teachers %}
                <tr>
                <td style="text-align: center">{{ teacher.id }}</td>
                <td>{{ teacher.first_name }}</td>
                <td>{{ teacher.last_name }}</td>
                <td style="text-align: center">{{ teacher.age }}</td>
                <td>{{ teacher.rank }}</td>
                <td>{{ teacher.phone }}</td>
                <td>{{ teacher.email }}</td>
                <td>{{ teacher.group }}</td>
                <td style="text-align: center">
                <a href="{% url 'teachers:edit' pk=teacher.id %}"><button class="button-table"> edit </button></a>
                <a href="{% url 'teachers:remove' pk=teacher.id %}"><button class="button-table-del"> delete </button></a><br>
                </td>
                </tr>
            {% endfor %}
        </table>
    </div>>
    <div class="pagination">
         <span class="step-links">
             {% if teachers.has_previous %}
             <a href="?page=1">&laquo; first</a>
             <a href="?page={{ teachers.previous_page_number }}">previous</a>
             {% endif %}

             <span class="current">
                 Page {{ teachers.number }} of {{ teachers.paginator.num_pages }}.
             </span>

             {% if teachers.has_next %}
             <a href="?page={{ teachers.next_page_number }}">next</a>
             <a href="?page={{ teachers.paginator.num_pages }}">last &raquo;</a>
             {% endif %}
         </span>
    </div>

</body>
</html>