src/groups/urls.py
from django.urls import path

from groups import views

app_name = 'groups'

urlpatterns = [
    path('', views.home, name='home'),
    path('index/', views.group_app, name='index'),
    path('list/', views.groups, name='list'),
    path('create/', views.create_group, name='create'),
    path('edit/<int:pk>/', views.edit_group, name='edit'),
    path('remove/<int:pk>/', views.remove_group, name='remove'),
    path('generate/', views.generate_group, name='generate'),
]

src/students/urls.py
from django.urls import path

from students import views

app_name = 'students'

urlpatterns = [
    path('', views.home, name='home'),
    path('index/', views.students_app, name='index'),
    path('list/', views.students, name='list'),
    path('create/', views.create_student, name='create'),
    path('edit/<int:pk>/', views.edit_student, name='edit'),
    path('remove/<int:pk>/', views.remove_student, name='remove'),
    path('generate/', views.generate_student, name='generate'),
    path('contact/', views.contact_us, name='contact'),
]

src/students_tracker/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path

from students import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.home, name='home'),
    path('students/', include('students.urls'), name='students'),
    path('teachers/', include('teachers.urls'), name='teachers'),
    path('groups/', include('groups.urls'), name='groups'),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

    urlpatterns += [url(r'^silk/', include('silk.urls', namespace='silk'))]

src/students/models.py
import random

from django.db import models

from faker import Faker


class Student(models.Model):
    FRESHMAN = 'FR'
    SOPHOMORE = 'SO'
    JUNIOR = 'JR'
    SENIOR = 'SR'
    YEAR_IN_SCHOOL_CHOICES = [
        (FRESHMAN, 'Freshman'),
        (SOPHOMORE, 'Sophomore'),
        (JUNIOR, 'Junior'),
        (SENIOR, 'Senior'),
    ]
    grade = models.CharField(
        max_length=2,
        choices=YEAR_IN_SCHOOL_CHOICES,
        default=FRESHMAN,
    )
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    age = models.PositiveSmallIntegerField()  # models.IntegerField
    email = models.EmailField(unique=True, null=True)
    phone = models.CharField(max_length=24, default='')

    @property
    def full_name(self) -> str:
        return f'{self.first_name} {self.last_name}'

    def info(self) -> str:
        return f'{self.id} {self.first_name} {self.last_name} {self.age} {self.grade}'

    def inc_age(self) -> None:
        self.age += 1
        self.save()

    def __str__(self):
        return f'{self.id}, {self.full_name}'

    def __repr__(self):
        return f'{self.id}, {self.full_name}, {self.grade}'

    @classmethod
    def add_student(cls):
        fake = Faker()
        student = cls.objects.create(
            first_name=fake.first_name(),
            last_name=fake.last_name(),
            age=random.randint(18, 25),
            grade=random.choice(Student.YEAR_IN_SCHOOL_CHOICES)[1],
            email=fake.email(),
            phone=fake.phone_number(),
        )
        return student

    def save(self, *args, **kwargs):
        check_existence = Student.objects.all().only('email').filter(
            email__iexact=self.email
        ).exclude(
            email__iexact=self.email
        )
        if len(check_existence) != 0:
            raise Exception(f'{self.email} already exists')
        else:
            super().save(*args, **kwargs)


class Logger(models.Model):
    method = models.CharField(max_length=128)
    path = models.CharField(max_length=128)
    execution_time = models.DecimalField(max_digits=4, decimal_places=4)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.method}, {self.path}, {self.execution_time}, {self.created}'

    @staticmethod
    def _check_log():
        with open('middleware.log', 'a') as file:
            logger_queryset = Logger.objects.all()
            for log_data in logger_queryset:
                file.write(
                    f' {log_data.id},'
                    f' {log_data.method},'
                    f' {log_data.path},'
                    f' {log_data.execution_time},'
                    f' {log_data.created},'
                    f' \n')

src/students/forms.py
from django import forms

from students.models import Student
from students.tasks import email_sender


class StudentCreateForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = (
            'first_name',
            'last_name',
            'age',
            'grade',
            'email',
            'phone',
        )

    # def clean_phone(self):  # clean_ + field
        """
        auto-cleaner phone after form submit
        """
    #     phone = self.cleaned_data['phone']
    #     cleaned_phone = ''.join(i for i in phone if i.isdigit())
    #     return cleaned_phone

    def clean_age(self):  # clean_ + field
        course = self.cleaned_data['age']
        if not 18 <= course <= 99:
            raise forms.ValidationError('You are either too young or too old')
        return course

    def clean_phone(self):  # clean_ + field
        phone = self.cleaned_data['phone']
        if not phone.isdigit():
            raise forms.ValidationError('Phone number must contain only digits')
        return phone

    def clean_first_name(self):
        first_name = self.cleaned_data['first_name']
        if not first_name.isalpha():
            raise forms.ValidationError('First name must contain only letters')
        return first_name

    def clean_last_name(self):  # Petr 1 - not allowed
        last_name = self.cleaned_data['last_name']
        if not last_name.isalpha():
            raise forms.ValidationError('Last name must contain only letters')
        return last_name

    def clean_email(self):
        email = self.cleaned_data['email']
        check_existence = Student.objects.all().only('email').filter(email__iexact=email).exclude(email__iexact=email)
        if len(check_existence) != 0:
            raise forms.ValidationError(f'{email} already exists')
        return email


class ContactUsForm(forms.Form):
    CHOICES = [('-', '-'),
               ('Service related', 'Service related'),
               ('New comers', 'New comers'),
               ]  # to separate departments
    issue = forms.ChoiceField(choices=CHOICES, required=True)  # will appear in email TITLE alongside form.title
    username = forms.CharField(max_length=36, required=True, label='Name')
    email = forms.EmailField(max_length=36, required=True)
    subject = forms.CharField(max_length=36, required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

    field_order = ['username', 'email', 'subject', 'issue', 'message', ]

    def save(self):
        issue = self.cleaned_data["issue"]
        username = self.cleaned_data["username"]
        subject = self.cleaned_data["subject"]
        message = self.cleaned_data["message"]
        email = self.cleaned_data["email"]
        # rabbitMQ
        return email_sender.apply_async(args=[issue, username, subject, message, email], countdown=3)
        # async - for fun
        # rabbitMQ

    def clean_username(self):
        username = self.cleaned_data['username']
        if not username.isalpha():
            raise forms.ValidationError('Field name must contain only letters')
        return username

    def clean_issue(self):
        issue = self.cleaned_data['issue']
        if issue in '-':
            raise forms.ValidationError('Choose related topic')
        return issue

src/students/views.py
import random

from django.apps import apps
from django.contrib import messages
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from faker import Faker

from students.filters import StudentFilter
from students.forms import ContactUsForm, StudentCreateForm
from students.models import Student

from utils import clear_table_parser, parse_usr_value


def home(request):
    return render(request, 'index.html')


def students_app(request):
    return render(request, 'student_index.html')


def students(request):
    count = Student.objects.count()
    students_queryset_list = Student.objects.all().select_related('group')

    st_filter = StudentFilter(request.GET, queryset=students_queryset_list)
    students_queryset_list = st_filter.qs

    paginator = Paginator(students_queryset_list, 10)
    page = request.GET.get('page')
    try:
        students_queryset = paginator.page(page)
    except PageNotAnInteger:
        students_queryset = paginator.page(1)
    except EmptyPage:
        students_queryset = paginator.page(paginator.num_pages)

    context = {'students': students_queryset, 'count': count, 'st_filter': st_filter}

    return render(request, 'student_list.html', context=context)


def generate_student(request):
    fake = Faker()
    student = Student.objects.create(
        first_name=fake.first_name(),
        last_name=fake.last_name(),
        age=random.randint(18, 25),
        grade=random.choice(Student.YEAR_IN_SCHOOL_CHOICES)[1],
        email=fake.email(),
        phone=fake.phone_number(),
    )

    return render(request, 'generate_student.html', context={'student': student})


def sheets(request):  # abandoned
    sheets_reg = [
        m._meta.db_table for c in apps.get_app_configs() for m in c.get_models()
    ]
    response = f'Current sheets: {sheets_reg}<br/>'
    return HttpResponse(response)


def clear_sheet(request):  # abandoned
    """
    :param request:
    /clear_sheet/st/?clear=1&sheet_name=Student
    :return:
    Wipes out all rows in sheet Student
    """
    req_clear_sheet = clear_table_parser(request.GET['clear'], 'digit')
    sheet_name = clear_table_parser(request.GET['sheet_name'], 'alpha')
    response = f'Selected SHEET has been cleared:<br/>'
    if sheet_name == 'Student':
        if req_clear_sheet == 1:
            Student.objects.all().delete()
            response += f'{sheet_name}'
    return HttpResponse(response)


def delete_row(request):  # abandoned
    """
    :param request:
    /del_row/st/?id=49
    :return:
    Wipes out selected row from current table
    """
    req_clear_row = clear_table_parser(request.GET['id'], 'id')
    try:
        Student.objects.filter(id=req_clear_row).delete()
        response = f'Selected ROW has been cleared: {req_clear_row}<br/>'
    except Exception:
        response = f'Something went wrong. Enter valid value'

    return HttpResponse(response)


def query_filter(request):  # abandoned
    """
    :param request:
    /filter/st/?age=22&first_name=Elizabeth
    /filter/st/?order_by=age
    /filter/st/?age=20&order_by=-first_name
    :return:
    list of students with params equal to request:
    id, first_name, last_name, age, grade, etc..
    """
    params = [
        'age',
        'age__gt',
        'age__lt',
        'age__lte',
        'age__gte',
        'first_name',
        'first_name__exact',
        'first_name__startswith',
        'first_name__endswith',
        'last_name',
        'last_name__startswith',
        'last_name__endswith',
        'grade',
        'grade__startswith',
        'grade__endswith',
        'id',
        'order_by',
    ]

    response = f'Selected data:<br/>'
    students_queryset = Student.objects.all()

    # simple filter

    for param in params:
        value = request.GET.get(param)
        if param not in 'order_by':
            if value:
                students_queryset = students_queryset.filter(**{param: value})

    # adds filter order_by

    for param in params:
        value = request.GET.get(param)
        if param in 'order_by':
            if value:
                students_queryset = students_queryset.order_by(value)

    for student in students_queryset:
        response += student.info() + '<br/>'

    return render(request, 'student_list.html', context=students_queryset)


def generate_students(request):  # abandoned
    """
    :param request:
    PATH: /generate-students/st/?count=10
    :return:
    list of 10 students: id, first_name, last_name, age.
    """
    fake = Faker()
    rand_students_queryset = Student.objects.all()
    response = f'Students:<br/>'
    usr_value = parse_usr_value(request.GET['count'])
    if type(usr_value) is str:
        return HttpResponse(usr_value)

    for _ in range(usr_value):
        Student.objects.create(
            first_name=fake.first_name(),
            last_name=fake.last_name(),
            age=random.randint(18, 25),
            grade=random.choice(Student.YEAR_IN_SCHOOL_CHOICES)[1],
            email=fake.email(),
            phone=fake.phone_number(),
        )

    for student in rand_students_queryset:
        response += student.info() + '<br/>'

    return HttpResponse(response)


def create_student(request):
    from students.forms import StudentCreateForm

    if request.method == 'POST':

        form = StudentCreateForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, 'You have successfully created student')
            return HttpResponseRedirect(reverse('students:list'))
    else:
        form = StudentCreateForm()

    context = {'create_form': form}

    return render(request, 'create.html', context=context)


def edit_student(request, pk):
    student = get_object_or_404(Student, id=pk)
    if request.method == 'POST':

        form = StudentCreateForm(request.POST, instance=student)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('students:list'))
    else:
        form = StudentCreateForm(instance=student)

    context = {'form': form, 'student': student}

    return render(request, 'edit.html', context=context)


def remove_student(request, pk):
    student = get_object_or_404(Student, id=pk)
    student.delete()
    messages.success(request, 'You have successfully deleted student')

    return HttpResponseRedirect(reverse('students:list'))


def contact_us(request):
    if request.method == 'POST':
        form = ContactUsForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'You have successfully submitted form')
    else:
        form = ContactUsForm()
    return render(request, 'contact.html', context={'form': form})

# def slow(request):
#     slow_func.delay()
#     return HttpResponse('SLOW')

src/students/templates/contact.html
<!DOCTYPE html>
{% load static %}
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Student Tracker</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/student.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Righteous&subset=latin,cyrillic" rel="stylesheet"
          type="text/css">
    <link href="{% static 'css/student.css' %}" type="text/css" rel="stylesheet">
</head>
<body>
    <div class="header" id="st-header">
        <h1>STUDENT TRACKER</h1>
    </div>
    {% include 'messages.html' %}
     <div class="content">
         <h3 style="color: green"> Send us a message </h3>
        <form method="post" action="">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="button" type="submit"> submit</button>
            <button class="button" type="reset"> reset</button>
            <a href="{% url 'home' %}">
                <button class="button" type="button"> cancel</button>
            </a>
        </form>
     </div>
</body>
</html>

src/students/templates/create.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Students</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/student.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Righteous&subset=latin,cyrillic" rel="stylesheet"
          type="text/css">
    <link href="{% static 'css/student.css' %}" type="text/css" rel="stylesheet">
</head>
<body>

<div class="page-header">
    <h1>Create student</h1>
</div>
<div class="content-container">
    {% include 'messages.html' %}
    <a href="{% url 'students:index' %}" style="font-size: 20px;">Students app</a>
    <form method="post" style="font-size: 15px;">
            {% csrf_token %}
            {{ create_form.as_p }}
            <button class="button" type="submit"> submit</button>
            <button class="button" type="reset"> reset </button>
            <a href="{% url 'students:list' %}"><button class="button" type="button"> cancel </button></a>
    </form>
</div>
</body>
</html>

src/students/templates/create_student.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hillel project</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/student.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Righteous&subset=latin,cyrillic" rel="stylesheet"
          type="text/css">
</head>
<body>

<div class="page-header">
    <h1><a>Create student</a></h1>
</div>
<div class="content container">
    <form method="post" style="font-size: 15px;">
        {% csrf_token %}
        {{ create_form.as_p }}
        <button type="submit"> Submit</button>
    </form>
</div>


</body>
</html>

src/students/templates/edit.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Students</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/student.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Righteous&subset=latin,cyrillic" rel="stylesheet"
          type="text/css">
    <link href="{% static 'css/student.css' %}" type="text/css" rel="stylesheet">
</head>
<body>
<div class="page-header">
    <h1>Edit student</h1>
</div>
<div class="content-container">
    {% include 'messages.html' %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="button" name="submit" type="submit"> submit</button>
        <button class="button" type="reset"> reset </button>
        <a href="{% url 'students:list' %}"><button class="button" type="button"> cancel </button></a>
        <a href="{% url 'students:remove' pk=student.id %}"><button class="button-del" type="button"> delete </button></a><br>

    </form>
</div>
</body>
</html>

src/students/templates/generate_student.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hillel project</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/student.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Righteous&subset=latin,cyrillic" rel="stylesheet"
          type="text/css">
    <link href="{% static 'css/student.css' %}" type="text/css" rel="stylesheet">
</head>
<body>
    <div class="page-header">
        <h1>Student Info</h1>
    </div>
    <div class="content-container">
        <h3 align="center">Student: {{ student.info }}</h3>
        <a href="{% url 'students:generate' %}"><button class="button" name="submit" type="submit"> generate </button></a>
        <a href="{% url 'students:index' %}"><button class="button" name="submit" type="submit"> cancel </button></a>
    </div>

</body>
</html>

src/students/templates/messages.html
{% if messages %}
    {% for message in messages %}
       <div class="alert alert-{{ message.tags }} m-2" id="msg" role="alert">
           {{ message }}
       </div>
    {% endfor %}
{% endif %}

src/students/templates/st_index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create student</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/student.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Righteous&subset=latin,cyrillic" rel="stylesheet"
          type="text/css">
    <link href="student.css" type="text/css" rel="stylesheet">
</head>
<body>
    <div class="page-header">
        <h1><a>Create forms:</a></h1>
    </div>
    <div class="post">
        <a href="/student/create_student/" style="font-size: 20px;">Create Student</a>
    </div>

</body>
</html>

src/students/templates/student_index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Student</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/student.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Righteous&subset=latin,cyrillic" rel="stylesheet"
          type="text/css">
    <link href="{% static 'css/student.css' %}" type="text/css" rel="stylesheet">
</head>
<body>
    <div class="header" id="st-header">
        <h1>Student APP</h1>
    </div>
    <div class="content">
        <ul>
            <li><a href="{% url 'home' %}" style="font-size: 20px;">Home</a></li>
            <li><a href="{% url 'students:list' %}" style="font-size: 20px;">Students List</a></li>
            <li><a href="{% url 'students:create' %}" style="font-size: 20px;">Create student</a></li>
            <li><a href="{% url 'students:generate' %}" style="font-size: 20px;">Generate student</a></li>
            <li style="float:right"><a class="active" href="#">About</a></li>
        </ul>
    </div>
</body>
</html>

src/students/templates/student_list.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Students</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/student.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Righteous&subset=latin,cyrillic" rel="stylesheet"
          type="text/css">
    <link href="{% static 'css/student.css' %}" type="text/css" rel="stylesheet">
</head>
<body>
    <div class="header" id="st-header">
        <h1>Students list</h1>
    </div>
    {% include 'messages.html' %}
    <div class="links" align="center">
        <a href="{% url 'home' %}" style="font-size: 20px;">Home &ensp;</a>
        <a href="{% url 'students:index' %}" style="font-size: 20px;">Students app &ensp;</a>
        <a href="{% url 'students:create' %}" style="font-size: 20px;">Create student &ensp;</a>
    </div>
    <div class="content">
        <h2>Students: {{ count }}</h2>
        <div>
            <form method="get">
                {{st_filter.form}}
                <button class="button-table" type="submit">Search</button>
            </form>
        </div>
        <table style="width:100%">
            <tr>
                <th>Id</th>
                <th>First name</th>
                <th>Last name</th>
                <th >Age</th>
                <th>Grade</th>
                <th>Phone</th>
                <th style="width:20%">Email</th>
                <th>Group</th>
                <th style="width:200px">Action</th>
                </tr>
            {% for student in students %}
                <tr>
                <td style="text-align: center">{{ student.id }}</td>
                <td>{{ student.first_name }}</td>
                <td>{{ student.last_name }}</td>
                <td style="text-align: center">{{ student.age }}</td>
                <td>{{ student.grade }}</td>
                <td>{{ student.phone }}</td>
                <td>{{ student.email }}</td>
                <td>{{ student.group }}</td>
                <td style="text-align: center">
                <a href="{% url 'students:edit' pk=student.id %}"><button class="button-table"> edit </button></a>
                <a href="{% url 'students:remove' pk=student.id %}"><button class="button-table-del"> delete </button></a><br>
                </td>
                </tr>
            {% endfor %}
        </table>
    </div>>
    <div class="pagination">
         <span class="step-links">
             {% if students.has_previous %}
             <a href="?page=1">&laquo; first</a>
             <a href="?page={{ students.previous_page_number }}">previous</a>
             {% endif %}

             <span class="current">
                 Page {{ students.number }} of {{ students.paginator.num_pages }}.
             </span>

             {% if students.has_next %}
             <a href="?page={{ students.next_page_number }}">next</a>
             <a href="?page={{ students.paginator.num_pages }}">last &raquo;</a>
             {% endif %}
         </span>
    </div>
    <script>
        window.onscroll = function() {sticky_header()};

        var header = document.getElementById("st-header");
        var sticky = header.offsetTop;

        function sticky_header() {
          if (window.pageYOffset > sticky) {
            header.classList.add("sticky");
          } else {
            header.classList.remove("sticky");
          }
        }
    </script>
</body>
</html>